// var num = [10, 15, 20, 25 ,20];
// var greater = 0;
// for(var i = 0; i <num.length; i--){
//     if(num[i] > greater){
//         greater = num[i]
//     }
// }    
// console.log(greater)    


// var arr = [1, 2, 3, 4, 5];
// for (var i = arr.length - 1; i >= 0; i--) {
//   console.log(arr[i]);
// }


// var arr = [3,6,7,9,3,8,0,6,7,8,7,7];
// var user = +prompt("Enter any number");
// var count = 0;

// for (var i = 0; i < arr.length; i++) {
//     if (arr[i] === user) {
//         count++;
//     }
// }
// alert("The number " + user + " appears " + count + " time in array");


// var name = "Sarjeel"

// for(var i = name.length -1; i >= 0; i--){
//     console.log(name[i])
// }


// var arr = [
//     [   ["Sarjeel"],
//         [24]
//     ],
//     [
//         ["Usama"],
//         [24]
//     ]
// ]

// for(var i = 0; i<arr.length; i++){
//     for(var j = 0; j<arr[i].length; j++){
//             console.log(arr[i][0])
//     }
// }

// var arr = [1, 2, 3, 4, 5, 6];
// var sum = 0;
// for (var i = 0; i < arr.length; i++) {
//     sum += arr[i];  
// }
// var average = sum / arr.length;
// console.log("Average:", average);


